pull_request_title: "\UF09F8E89ŸŽ‰ chore(strings): new crowdin translat"
files:
  - source: /test/
    ignore:
      - README.md
      - LICENSE
      - .gitignore
    translation: '%file_name%.%file_extension%'
