pull_request_title: '🎉 chore(strings): new crowdin translation'
files:
  - source: /en/
    ignore:
      - README.md
      - LICENSE
      - .gitignore
    translation: '%file_name%.%file_extension%'
